#!/bin/bash

# (c) Patryk Czarnik
# Distributed under MIT License. See LICENCE file in the root directory for details.

usage="vid-concat [-o outfile] infile [infile...]"

if [ $# -eq 0 ]
then
  echo "$usage"
  exit 1
fi

if [ "$1" == '-o' ]
then
  if [ $# -lt 3 ]
  then
    echo "$usage"
    exit 1
  fi
  out="$2"
  shift 2
else
  out="out.avi"
fi

mencoder -oac copy -ovc copy -forceidx -o "$out" "$@"
