#!/bin/bash

# (c) Patryk Czarnik
# Distributed under MIT License. See LICENCE file in the root directory for details.

# This script processes a list of video files optionally cutting their fragments
# and then passes the video chunks to another script (which usually merges them).

usage="vid-list command [options]
This script reads lines from the standard input,
each line describes a single video chunk and should be in the following format:
file [start [length]]
(square brackets denote optional fragments).
file is a path to the source video file,
start and length denote time boundaries, they should be given in an mencoder-accepted format
(number of seconds is always available).
The video chunks are passed as arguments to the command together with all the given options.
"

tmpdir=.
# tmpdir=/tmp

cmd="$1"
shift
files=""
tmpfiles=""
n=0

while read file start len rest
do
  n=$(($n + 1))
  if [ -z "$start" ]
  then
    files="$files $file"
  else
    opts=" -nosound -ovc copy -ss $start"
    if [ -n $len ]
    then opts="$opts -endpos $len"
    fi
    tmpfile=`printf "%s/chunk%03d.avi" $tmpdir $n`
    echo "Cutting a chunk from $file into $tmpfile"
    mencoder $opts -o "$tmpfile" "$file"
    files="$files $tmpfile"
    tmpfiles="$tmpfiles $tmpfile"
  fi  
done

echo "Processing files $files"

$cmd "$@" $files

echo "Deleting temporary files $tmpfiles"
rm $tmpfiles
