#!/bin/bash

# (c) Patryk Czarnik
# Distributed under MIT License. See LICENCE file in the root directory for details.

all : mulcat

mulcat : mulcat.c
	gcc -o mulcat mulcat.c

clean :
	rm -f mulcat *.o
