#!/bin/bash

# (c) Patryk Czarnik
# Distributed under MIT License. See LICENCE file in the root directory for details.


# Prepares a specification for drawtext ffmpeg filter which prints some typical information on my road video.

# Command line processing
usage="myvid-prepare-text [options] < infile > outfile
Options:
  -h  -- prints usage message
  -S size -- output video size (the same as in vid-process)
"

BASEX=0
BASEY=664
SIZE1=22
SIZE2=26
SIZE3=28
SIZE4=40
FONT=/usr/share/fonts/truetype/DejaVuSans.ttf
FONTT=/usr/share/fonts/truetype/DejaVuSansMono.ttf
FONTC=/usr/share/fonts/truetype/DejaVuSansCondensed.ttf
FONTB=/usr/share/fonts/truetype/DejaVuSans-Bold.ttf
FONTI=/usr/share/fonts/truetype/DejaVuSans.ttf

osize=t720

while getopts "hs:e:z" opt; do
  case "$opt" in
  h|\?)
     echo "$usage"
     exit 1
     ;;
  S) osize="$OPTARG"
     ;;
  i) infile="$OPTARG"
     ;;
  o) outfile="$OPTARG"
     ;;
  esac
done

shift $(($OPTIND - 1))


# The order of icon names here must corelate with the order of image sources in the vid-process command
icons="junc exit mop ppo logo"
declare -A icon_img_cond
for i in $icons
do
  icon_img_cond[$i]=0
done

icons_txt=


function echo_text() {
  echo -n ",drawtext=enable='between(t,$from,$to)':x=$(($BASEX + x)):y=$(($BASEY + y)):fontcolor=$color:fontfile=$font:fontsize=$size:text=$text"
  if [ -n "$boxcolor" ]
  then
    echo -n ":box=1:boxborderw=5:boxcolor=$boxcolor"
  fi
}

function draw_box() {
  echo -n ",drawbox=enable='between(t,$from,$to)':x=$(($BASEX + x)):y=$(($BASEY + y)):w=$w:h=$h:t=$t:color=$color"
}

function make_icons() {
  for i in $icons
  do
    echo -n ",overlay=enable='${icon_img_cond[$i]}':x=$(($BASEX + 120)):y=$(($BASEY))"
  done
  echo -n $icons_txt
}

function remember_icon() {
  x=200
  y=18
  color=#CCEEFF
  size=$SIZE2
  font="$FONTC"
  icons_txt="$icons_txt,drawtext=enable='between(t,$from,$to)':x=$(($BASEX + x)):y=$(($BASEY + y)):fontcolor=$color:fontfile=$font:fontsize=$size:text=$text"
  icon_img_cond[$1]="${icon_img_cond[$1]}+between(t,$from,$to)"
}


echo -n "null"

while read keyword from to arg text
do
  case "$keyword" in
  (road)
    case "$arg" in
    (DK) color=#FF4444;;
    (DW) color=#FFFF33;;
    (S) color=#22FF77;;
    (A) color=#44AAFF;;
    (*) color=#FFFFFF;;
    esac
    
    x=8
    y=4
    w=100
    h=48
    t=3
    draw_box

    x=16
    y=12
    size=$SIZE4
    font="$FONTB"
    echo_text
  ;;
  (roadname)
    x=120
    y=18
    color=white
    size=$SIZE2
    font="$FONTC"
    echo_text
  ;;
  (city)
    x=480
    y=18
    color=white
    size=$SIZE3
    font="$FONTB"
    boxcolor=#048010
    echo_text
    boxcolor=
  ;;
  (icon)
    remember_icon $arg
  ;;
  (note)
  case "$arg" in
    (?1)
    x=500
    y=4
    ;;
    (?2)
    x=500
    y=30
    ;;
    (?3)
    x=680
    y=4
    ;;
    (?4)
    x=680
    y=30
    ;;
    (?5)
    x=760
    y=4
    ;;
    (?6)
    x=760
    y=30
    ;;
    (?7)
    x=920
    y=4
    ;;
    (?8)
    x=920
    y=30
    ;;
  esac
  case "$arg" in
    # achtung!
    (A?)
    color=#FF4455
    ;;
    # miasto
    (M?)
    color=#44FF55
    ;;
    # granice i inna geografia
    (G?)
    color=#6688FF
    ;;
    # energetyka i przemysł
    (E?)
    color=#CC77F8
    ;;
    # zabytek itp.
    (Z?)
    color=#BBAA33
    ;;
    # inna droga
    (D?)
    color=#EEFF44
    ;;
    # linia kolejowa
    (K?)
    color=#FFAA44
    ;;
    # inny obiekt
    (O?)
    color=#EEEEEE
    ;;
    (*)
    color=white
    ;;
  esac
    size=$SIZE1
    font="$FONTC"
    echo_text
  ;;
  esac
done

if [ -n "$icons_txt" ]
then
  make_icons
fi
