#!/bin/bash

# (c) Patryk Czarnik
# Distributed under MIT License. See LICENCE file in the root directory for details.

# Command line processing
usage="vid-drop-frag [options] infile [infile...]
Copies a continuos fragment of raw A/V stream (without decoding/encoding).
The fragment may spread over a number of files in the input.
Options:
  -h  -- prints usage message
  -o output_file -- sets output file
  -s secs -- start offset (in the first source video)
  -e secs -- end offset  (in the last source video)
"

while getopts "ho:s:e:" opt; do
  case "$opt" in
  h|\?)
     echo "$usage"
     exit 1
     ;;
  o) output="$OPTARG"
     ;;
  s) start="$OPTARG"
     ;;
  e) end="$OPTARG"
     ;;
  esac
done

shift $(($OPTIND - 1))


# Preparing the list of input files in a separate file - for "concat" demuxer
SPEC_FILE="vid-drop-frag-spec.txt"

> $SPEC_FILE

n=0
for file in "$@"
do
  n=$(($n + 1))
  echo "file '$file'" >> $SPEC_FILE
  if [ -n "$start" ]
  then
    echo "inpoint $start" >> $SPEC_FILE
    start=
  fi
done
if [ -n "end" ]
then
  echo "outpoint $end" >> $SPEC_FILE
  end=
fi


# Preparing and invoking the ffmpeg command  
if [ -z "$output" ]
then
output="out.mp4"
fi

command="ffmpeg -noaccurate_seek -y -f concat -i $SPEC_FILE -c copy $output"

echo $command

$command
